name: Cloudtype Github Actions - Deploy
author: Cloudtype Inc
description: Deploy apps to Cloudtype.
inputs:
  token:
    description: Cloudtype Access Token
    required: true
  endpoint:
    description: API Endpoint
    required: false
  project:
    description: Project Name
    required: false
  stage:
    description: Stage Name
    required: false
  allstages:
    description: Deploy to All Stages
    required: false
  file:
    description: Description File
    required: false
  json:
    description: Description JSON Text
    required: false
  yaml:
    description: Description Yaml Text
    required: false
runs:
  using: node20
  main: dist/index.js
