on:
  workflow_dispatch:
jobs:
  hello-my-actions:
    runs-on: ubuntu-latest
    name: Cloudtype Deploy
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: ./
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: test
          stage: main,dev
          yaml: |-
            name: myapp
            app: web
            options:
              git:
                url: https://github.com/cloudtype/example-react.git
              docbase: /build
